rabbit1:
    image: rabbitmq:3.7.8-management
    hostname: rabbit1
    environment:
        - RABBITMQ_ERLANG_COOKIE=m1D31LcPo7
        - RABBITMQ_NODENAME=rabbit@rabbit1
    volumes:
        - /D/.docker/rabbitmq/node1:/var/lib/rabbitmq/mnesia/
    ports:
        - "5672:5672"
        - "15672:15672"
rabbit2:
    image: rabbitmq:3.7.8-management
    hostname: rabbit2
    links:
        - rabbit1
    environment:
        - RABBITMQ_ERLANG_COOKIE=m1D31LcPo7
        - RABBITMQ_NODENAME=rabbit@rabbit2
    volumes:
        - /D/.docker/rabbitmq/node2:/var/lib/rabbitmq/mnesia/
    ports:
        - "5673:5672"

# after deploying you should join second node to cluster:
# $ docker exec -it %stack_name%/rabbit2_1 /bin/bash
# $ rabbitmqctl stop_app
# $ rabbitmqctl join_cluster %stack_name%/rabbitq_1
# $ rabbitmqctl start_app

# and then you should set policy for mirroring queues:
# $ docker exec -it %stack_name%/rabbit1_1 /bin/bash
# $ rabbitmqctl set_policy HA ".*" '{"ha-mode": "all"}'